/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifam.visao;

import br.edu.ifam.modelo.Contato;
import br.edu.ifam.modelo.ContatoDao;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jucibs
 */
public class ContatoJFrame extends javax.swing.JFrame {

    // Atributos adicionados a classe
    ContatoDao contatoDao;
    List<Contato> listaDeContatos;
    int posicao;
    private boolean clicouBtnNovo;
    private Contato contato;

    /**
     * Creates new form ContatoJFrame
     */
    public ContatoJFrame() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        lblFoto.setVisible(true);
        // Intancia os atributos 
        contatoDao = new ContatoDao();
        listaDeContatos = contatoDao.getLista();
        // verificar se o listaDeContatos está preenchida e 
        // pega o primeiro contato para disponibilizar na tela.
        posicao = 0;
        if (listaDeContatos.size() > 0) {
            Contato c = listaDeContatos.get(posicao);
            carregaDadosParaTela(c);
        }
        contato = new Contato();
    }

    public void carregaDadosParaTela(Contato contato) {
        txtCodigo.setText(contato.getId() + "");
        txtNome.setText(contato.getNome());
        txtEnder.setText(contato.getEndereco());
        txtMail.setText(contato.getEmail());
        txtDtNasc.setText(contato.getDataNascimentoStr());
        if (contato.getFoto() != null) {
            System.out.println("tem foto "+contato.getId());
            ImageIcon foto=contato.getFoto();
            lblFoto.setIcon(foto);
            lblFoto.updateUI();
            foto.setImageObserver(lblFoto);
        } else {
            ImageIcon semFoto=new ImageIcon("C:\\Users\\Jucimar Brito\\OneDrive\\Documentos\\CursosMinistrados\\IFAM\\JavaBasico_Tecnico\\ProjFormNetbeans\\ExemploComBD\\src\\icones\\cameraFoto.png");
            lblFoto.setIcon(semFoto);
            lblFoto.updateUI();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcSelecionaFoto = new javax.swing.JFileChooser();
        lblCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEndere = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEnder = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        txtDtNasc = new javax.swing.JFormattedTextField();
        lblFoto = new javax.swing.JLabel();
        btnCarregaFoto = new javax.swing.JButton();

        jfcSelecionaFoto.setDialogTitle("Selecione Arquivo com Foto");
        jfcSelecionaFoto.setFileFilter(filtro);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Contatos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icones/xicaraCafe.png")).getImage());

        lblCodigo.setText("Código: ");

        jLabel2.setText("Nome:");

        lblEndere.setText("Endereço:");

        jLabel4.setText("E-Mail: ");

        jLabel5.setText("Dt. Nascimento:");

        txtCodigo.setEditable(false);

        txtNome.setEditable(false);

        txtEnder.setEditable(false);

        txtMail.setEditable(false);
        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });

        btnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/rewind.png"))); // NOI18N
        btnPrimeiro.setText("Primeiro");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/skip_backward.png"))); // NOI18N
        btnAnterior.setText("Anterior");

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/skip_forward.png"))); // NOI18N
        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fast_forward.png"))); // NOI18N
        btnUltimo.setText("Último");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/page_edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/search.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/remove.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/accept.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/repeat.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        txtDtNasc.setEditable(false);
        txtDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtDtNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtNascActionPerformed(evt);
            }
        });

        lblFoto.setBackground(new java.awt.Color(102, 102, 0));
        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cameraFoto.png"))); // NOI18N
        lblFoto.setText("Imagem");

        btnCarregaFoto.setText("Carregar Foto");
        btnCarregaFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregaFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addComponent(jLabel2)
                    .addComponent(lblEndere)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnder, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarregaFoto))
                        .addGap(398, 398, 398))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEditar, btnExcluir, btnNovo, btnPesquisar, btnSalvar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnterior, btnCancelar, btnPrimeiro, btnProximo, btnUltimo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEndere)
                            .addComponent(txtEnder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnterior)
                            .addComponent(btnProximo)
                            .addComponent(btnUltimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar)
                            .addComponent(btnPesquisar)
                            .addComponent(btnExcluir)
                            .addComponent(btnNovo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCarregaFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        posicao = 0;
        contato = listaDeContatos.get(posicao);
        carregaDadosParaTela(contato);
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        posicao++;
        if (posicao < listaDeContatos.size()) {
            contato = listaDeContatos.get(posicao);
            carregaDadosParaTela(contato);
        } else {
            JOptionPane.showMessageDialog(this, "Fim dos registros.",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            posicao = listaDeContatos.size() - 1;
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        posicao = listaDeContatos.size() - 1;
        contato = listaDeContatos.get(posicao);
        carregaDadosParaTela(contato);
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        clicouBtnNovo = true;
        // Limpar a tela
        limparTela();
        // hibilitar os jTextField para digitação
        liberarDigitacao();
        txtNome.requestFocus();
        // desabilitar os botões com exceção cancelar e Salvar
        desabilitarBtns();
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        contatoDao=new ContatoDao();
        if (clicouBtnNovo) {
            // Instancio um objeto contato para poder receber os dados da tela
            contato = new Contato();
            // Passa os dados digitados para o objeto Contato
            telaParaContato(contato);
            // Adiciona o contato na tabela Contatos no banco de dados
            contatoDao.adiciona(contato);
            // Para mentar a integridade do arraylist com o banco vamos 
            // carregar o arraylist novamente. Isto foi feito devido a 
            // não termos o id do contato gerado pelo banco.
            // Poderiamos deixar isto mais econômico apenas lendo o último registro 
            // do banco e adicionando no banco de dados.
            listaDeContatos = contatoDao.getLista();
            posicao = listaDeContatos.size() - 1;
            contato = listaDeContatos.get(posicao);
            contatoDao.gravaFoto(contato);
        } else {
            // Passa os dados digitados para o objeto Contato
            telaParaContato(contato);
            contatoDao.altera(contato);
        }

        carregaDadosParaTela(contato);
        bloquearDigitacao();
        habilitarBtns();
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
    }//GEN-LAST:event_btnSalvarActionPerformed
    /*  
     * Tem a finalidade de cancelar qualquer coisa que o usuário está 
     * fazendo e voltar a situação anterior antes do clique no botão cancelar
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // vamos recuperar o contato que estava em uso e colocar na tela
        Contato c = listaDeContatos.get(posicao);
        carregaDadosParaTela(c);
        habilitarBtns();
        bloquearDigitacao();
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        clicouBtnNovo = false;
        desabilitarBtns();
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        liberarDigitacao();
        txtNome.requestFocus();
        telaParaContato(contato);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Desejas cancelar o registro corrente? ",
                "Exclusão de Contatos", JOptionPane.WARNING_MESSAGE)
                == JOptionPane.OK_OPTION) {
            contatoDao.remove(contato);
            listaDeContatos = contatoDao.getLista();
            posicao = listaDeContatos.size() - 1;
            contato = listaDeContatos.get(posicao);
            carregaDadosParaTela(contato);

        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String strId = JOptionPane.showInputDialog(this, "Digite um id ");
        long id = Long.parseLong(strId);
        posicao = 0;
        while (posicao < listaDeContatos.size()) {
            contato = listaDeContatos.get(posicao);
            if (contato.getId() == id) {
                carregaDadosParaTela(contato);
                return;
            }
            posicao++;
        }
        JOptionPane.showMessageDialog(this, "Id pesquisado não existe",
                "Atenção", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnCarregaFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregaFotoActionPerformed
        FileInputStream fis;
        int estado = jfcSelecionaFoto.showOpenDialog(this);

        if (estado == JFileChooser.APPROVE_OPTION) {
            try {
                fis = new FileInputStream(jfcSelecionaFoto.getSelectedFile());
                Image icono = ImageIO.read(jfcSelecionaFoto.getSelectedFile()).
                        getScaledInstance(lblFoto.getWidth(),
                                lblFoto.getHeight(), Image.SCALE_DEFAULT);
                lblFoto.setIcon(new ImageIcon(icono));
                lblFoto.updateUI();
                contato.setFoto(new ImageIcon(icono));
                contato.setFotoFile(new File(jfcSelecionaFoto.getSelectedFile().getPath()));
            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(this, "Arquivo não encontrado!",
                    "ERRO: "+e.getMessage(), JOptionPane.ERROR_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Erro de I/O.",
                    "ERRO: "+e.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCarregaFotoActionPerformed

    private void txtDtNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtNascActionPerformed

    private void telaParaContato(Contato c) {
        if (txtCodigo.getText().trim().length()>0){
            c.setId(Long.parseLong(txtCodigo.getText()));
        }
        c.setNome(txtNome.getText());
        c.setEndereco(txtEnder.getText());
        c.setEmail(txtMail.getText());
        // Converte String para Data
        String strData = txtDtNasc.getText();
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            cal.setTime(sdf.parse(strData));
            c.setDataNascimento(cal);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro de Conversão",
                    "Informe uma data válida.", JOptionPane.ERROR_MESSAGE);
            txtDtNasc.setText("");
            txtDtNasc.requestFocus();
            ex.printStackTrace();
        }
         contato.setFoto((ImageIcon)lblFoto.getIcon());
    }

    private void limparTela() {
        txtCodigo.setText("");
        txtNome.setText("");
        txtMail.setText("");
        txtDtNasc.setText("");
        txtEnder.setText("");
    }

    private void liberarDigitacao() {
        txtNome.setEditable(true);
        txtMail.setEditable(true);
        txtDtNasc.setEditable(true);
        txtEnder.setEditable(true);
    }

    private void bloquearDigitacao() {
        txtNome.setEditable(false);
        txtMail.setEditable(false);
        txtDtNasc.setEditable(false);
        txtEnder.setEditable(false);
    }

    public void desabilitarBtns() {
        btnPrimeiro.setEnabled(false);
        btnProximo.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnUltimo.setEnabled(false);
        btnNovo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
    }

    
    public void habilitarBtns() {
        btnPrimeiro.setEnabled(true);
        btnProximo.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnUltimo.setEnabled(true);
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContatoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContatoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContatoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContatoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContatoJFrame().setVisible(true);
            }
        });
    }
    
    FileNameExtensionFilter filtro=new FileNameExtensionFilter("Arquivos de Imagem *.png, *.bmp", "*.png, *.bmp");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCarregaFoto;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFileChooser jfcSelecionaFoto;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEndere;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtDtNasc;
    private javax.swing.JTextField txtEnder;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
